---
custom: [
  'https://www.bitcoinqrcodemaker.com/?style=bitcoin&address=145HwyQAcv4vrzUumJhu7nWGAVBysX9jJH&prefix=on',
  'https://paypal.me/fabasoad',
  'https://qr.paypay.ne.jp/p2p01_YjGKM1AQ3UY6PoQN'
]
github: ['fabasoad']
ko_fi: fabasoad
liberapay: fabasoad
