---
name: 'Setup Jolie'
author: Yevhen Fabizhevskyi
description: 'Set up a specific version of Jolie.'
branding:
  icon: terminal
  color: gray-dark
inputs:
  version:
    description: 'Jolie version.'
    required: false
    default: '1.10.13'
runs:
  using: 'composite'
  steps:
    - name: Collect info
      id: info
      run: |
        JOLIE_INSTALLED=$(if command -v jolie >/dev/null 2>&1; then echo true; else echo false; fi)
        echo "JOLIE_INSTALLED=$JOLIE_INSTALLED" >> $GITHUB_OUTPUT
        BREW_INSTALLED=$(if command -v brew >/dev/null 2>&1; then echo true; else echo false; fi)
        echo "BREW_INSTALLED=$BREW_INSTALLED" >> $GITHUB_OUTPUT
        mkdir -p "$RUNNER_TEMP/jolie"
        echo "JOLIE_PATH=$RUNNER_TEMP/jolie" >> $GITHUB_OUTPUT
#        echo "DOWNLOAD_URL=https://github.com/jolie/jolie/releases/download/v${{ inputs.version }}/jolie-${{ inputs.version }}.jar" >> $GITHUB_OUTPUT
      shell: bash
    - name: Install jolie
      run: |
        git clone --depth 1 --branch v${{ inputs.version }} https://github.com/jolie/jolie.git
        cd jolie
        mvn install
        ls -A dist/
      shell: bash
      working-directory: ${{ steps.info.outputs.JOLIE_PATH }}
#    - name: Install jolie (Linux, macOS)
#      if: ${{ steps.info.outputs.JOLIE_INSTALLED == 'false' && runner.os != 'Windows' }}
#      run: |
#        wget -O jolie.jar ${{ steps.info.outputs.DOWNLOAD_URL }}
#        sudo java -jar jolie.jar
#        rm -f jolie.jar
#      shell: bash
#      working-directory: ${{ steps.info.outputs.JOLIE_PATH }}
#    - name: Install jolie (Windows)
#      if: ${{ steps.info.outputs.JOLIE_INSTALLED == 'false' && runner.os == 'Windows' }}
#      run: |
#        Invoke-WebRequest -URI ${{ steps.info.outputs.DOWNLOAD_URL }} -OutFile jolie.jar
#        if (-NOT ([Security.Principal.WindowsPrincipal][Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole([Security.Principal.WindowsBuiltInRole] "Administrator")) {
#          $arguments = "& '" +$myinvocation.mycommand.definition + "'"
#          Start-Process powershell -Verb runAs -ArgumentList $arguments
#        }
#        java -jar jolie.jar
#        Remove-Item -Path jolie.jar
#      shell: pwsh
#      working-directory: ${{ steps.info.outputs.JOLIE_PATH }}
