---
name: 'Setup Jolie'
author: Yevhen Fabizhevskyi
description: 'Set up a specific version of Jolie.'
branding:
  icon: terminal
  color: gray-dark
inputs:
  version:
    description: 'Jolie version.'
    required: false
    default: '1.10.13'
runs:
  using: 'composite'
  steps:
    - name: Collect info
      id: info
      run: |
        JOLIE_INSTALLED=$(if command -v jolie >/dev/null 2>&1; then echo true; else echo false; fi)
        echo "JOLIE_INSTALLED=$JOLIE_INSTALLED" >> $GITHUB_OUTPUT
        BREW_INSTALLED=$(if command -v brew >/dev/null 2>&1; then echo true; else echo false; fi)
        echo "BREW_INSTALLED=$BREW_INSTALLED" >> $GITHUB_OUTPUT
        mkdir -p "$RUNNER_TEMP/jolie"
        echo "JOLIE_PATH=$RUNNER_TEMP/jolie" >> $GITHUB_OUTPUT
      shell: bash
    - name: Install Jolie
      if: ${{ steps.info.outputs.JOLIE_INSTALLED == 'false' }}
      run: |
        wget -O jolie.jar https://github.com/jolie/jolie/releases/download/v${{ inputs.version }}/jolie-${{ inputs.version }}.jar
        java -jar jolie.jar
        env
        which jolie
      shell: bash
      working-directory: ${{ steps.info.outputs.JOLIE_PATH }}
