---
name: 'Setup Jolie'
author: Yevhen Fabizhevskyi
description: 'Set up a specific version of Jolie.'
branding:
  icon: terminal
  color: gray-dark
inputs:
  version:
    description: 'Jolie version.'
    required: false
    default: '1.10.13'
runs:
  using: 'composite'
  steps:
    - name: Collect info
      id: info
      run: |
        JOLIE_INSTALLED=$(if command -v jolie >/dev/null 2>&1; then echo true; else echo false; fi)
        echo "JOLIE_INSTALLED=$JOLIE_INSTALLED" >> $GITHUB_OUTPUT
        mkdir -p "$GITHUB_WORKSPACE/jolie"
        echo "JOLIE_PATH=$GITHUB_WORKSPACE/jolie" >> $GITHUB_OUTPUT
      shell: bash
    - name: Download jolie
      if: ${{ steps.info.outputs.JOLIE_INSTALLED == 'false' }}
      uses: actions/checkout@v3
      with:
        repository: jolie/jolie
        ref: v${{ inputs.version }}
        fetch-depth: 1
        path: jolie
        cache: maven
    - name: Install jolie
      if: ${{ steps.info.outputs.JOLIE_INSTALLED == 'false' }}
      run: |
        mvn install -Dmaven.test.skip=true
        bin_path="$(pwd)/bin_$(date '+%Y%m%d%H%M%S')"
        mkdir $bin_path
        echo "$bin_path" >> $GITHUB_PATH
        ./scripts/dev-setup.sh $bin_path
        echo "JOLIE_HOME=$bin_path/jolie-dist" >> $GITHUB_ENV
      shell: bash
      working-directory: ${{ steps.info.outputs.JOLIE_PATH }}
