---
name: Functional Tests

on:
  push:
    branches:
      - 'main'
  pull_request:

jobs:
  setup-jolie:
    name: Setup jolie
    timeout-minutes: 15
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu', 'windows', 'macos']
        version: ['1.11.0-beta', '1.10.13', '1.10.0']
        include:
          - version: '1.11.0-beta'
            java-version: '11'
          - version: '1.10.13'
            java-version: '11'
          - version: '1.10.0'
            java-version: '8'
        exclude:
          - os: 'windows'
            version: '1.10.13'
          - os: 'windows'
            version: '1.10.0'
          - os: 'macos'
            version: '1.11.0-beta'
    runs-on: ${{ matrix.os }}-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java-version }}
          distribution: zulu
      - name: Setup Jolie
        uses: ./
        with:
          version: ${{ matrix.version }}
      - name: Print version
        run: jolie --version
        shell: sh
  setup-jolie-alpine:
    name: Setup jolie
    timeout-minutes: 15
    strategy:
      fail-fast: false
      matrix:
        include:
          - image: 'alpine'
            version: '1.11.0-beta'
            java-version: '11'
          - image: 'alpine'
            version: '1.10.13'
            java-version: '11'
          - image: 'alpine'
            version: '1.10.0'
            java-version: '8'
    runs-on: ubuntu-latest
    container:
      image: adoptopenjdk/openjdk${{ matrix.java-version }}:${{ matrix.image }}-nightly-slim
    steps:
      - uses: actions/checkout@v3
      - name: Install tools
        run: |
          apk update
          apk add --update bash maven
        shell: sh
      - name: Setup Jolie
        uses: ./
        with:
          version: ${{ matrix.version }}
      - name: Print version
        run: jolie --version
        shell: sh
