---
name: Functional Tests

on: # yamllint disable-line rule:truthy
  push:
    branches:
      - "main"
  pull_request:

defaults:
  run:
    shell: sh

jobs:
  setup-jolie:
    name: Setup jolie (${{ matrix.os }})
    timeout-minutes: 20
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu", "windows"]
        version: ["1.11.2", "1.11.1", "1.11.0"]
    runs-on: ${{ matrix.os }}-latest
    steps:
      - name: Checkout ${{ github.repository }}
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: 11
          distribution: zulu
      - name: Setup Jolie
        uses: ./
        with:
          version: ${{ matrix.version }}
      - name: Print version
        run: jolie --version
  setup-jolie-alpine:
    name: Setup jolie (alpine)
    timeout-minutes: 15
    strategy:
      fail-fast: false
      matrix:
        version: ["1.11.2", "1.11.1", "1.11.0"]
    runs-on: ubuntu-latest
    container:
      image: adoptopenjdk/openjdk11:alpine-nightly-slim
    steps:
      - name: Checkout ${{ github.repository }}
        uses: actions/checkout@v4
      - name: Install tools
        run: |
          apk update
          apk add --update bash maven
      - name: Setup Jolie
        uses: ./
        with:
          version: ${{ matrix.version }}
      - name: Print version
        run: jolie --version
