---
name: Functional Tests

on:
  push:
    branches:
      - 'main'
      - 'fix-*'
      - 'feature-*'

jobs:
  setup-jolie:
    name: Setup jolie
    timeout-minutes: 15
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-latest', 'windows-latest', 'macos-latest']
        include:
          - version: '1.11.0-alpha'
            java-version: '11'
          - version: '1.10.13'
            java-version: '11'
          - version: '1.10.0'
            java-version: '8'
          - version: '1.8.1'
            java-version: '8'
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java-version }}
          distribution: adopt
      - name: Setup Jolie
        uses: ./
        with:
          version: ${{ matrix.version }}
      - name: Print version
        run: jolie --version
        shell: bash
  setup-jolie-alpine:
    name: Setup jolie (alpine-latest)
    timeout-minutes: 15
    strategy:
      fail-fast: false
      matrix:
        include:
          - version: '1.11.0-alpha'
            java-version: '11'
          - version: '1.10.13'
            java-version: '11'
          - version: '1.10.0'
            java-version: '8'
          - version: '1.8.1'
            java-version: '8'
    runs-on: ubuntu-latest
    container:
      image: alpine:latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java-version }}
          distribution: adopt
      - name: Setup Jolie
        uses: ./
        with:
          version: ${{ matrix.version }}
      - name: Print version
        run: jolie --version
        shell: bash
