---
name: Functional Tests

on:
  push:
    branches:
      - 'main'
      - 'fix-*'
      - 'feature-*'

jobs:
  setup-jolie:
    name: Setup jolie
    timeout-minutes: 15
    strategy:
      fail-fast: false
      matrix:
#        os: ['ubuntu-latest', 'windows-latest', 'macos-latest']
        os: ['ubuntu-latest']
#        version: ['1.11.0-alpha', '1.10.13']
        version: ['1.10.13']
        java-version: ['17']
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java-version }}
          distribution: adopt
      - name: Setup Jolie
        uses: ./
        with:
          version: ${{ matrix.version }}
      - name: Print version
        run: |
          env
          jolie --version
        shell: bash
