---
name: Functional Tests

on: # yamllint disable-line rule:truthy
  push:
    branches:
      - "main"
  pull_request:

defaults:
  run:
    shell: sh

jobs:
  setup-jolie:
    name: Setup jolie
    timeout-minutes: 20
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu", "windows", "macos"]
        version: ["1.11.1", "1.11.0", "1.10.13", "1.10.0"]
        include:
          - version: "1.11.1"
            java-version: "11"
          - version: "1.11.0"
            java-version: "11"
          - version: "1.10.13"
            java-version: "11"
          - version: "1.10.0"
            java-version: "8"
        exclude:
          - os: "windows"
            version: "1.10.13"
          - os: "windows"
            version: "1.10.0"
          - os: "macos"
            version: "1.11.0"
          - os: "macos"
            version: "1.11.1"
    runs-on: ${{ matrix.os }}-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java-version }}
          distribution: zulu
      - name: Setup Jolie
        uses: ./
        with:
          version: ${{ matrix.version }}
      - name: Print version
        run: jolie --version
  setup-jolie-alpine:
    name: Setup jolie
    timeout-minutes: 15
    strategy:
      fail-fast: false
      matrix:
        include:
          - image: "alpine"
            version: "1.11.1"
            java-version: "11"
          - image: "alpine"
            version: "1.11.0"
            java-version: "11"
          - image: "alpine"
            version: "1.10.13"
            java-version: "11"
          - image: "alpine"
            version: "1.10.0"
            java-version: "8"
    runs-on: ubuntu-latest
    container:
      image: adoptopenjdk/openjdk${{ matrix.java-version }}:${{ matrix.image }}-nightly-slim
    steps:
      - uses: actions/checkout@v4
      - name: Install tools
        run: |
          apk update
          apk add --update bash maven
      - name: Setup Jolie
        uses: ./
        with:
          version: ${{ matrix.version }}
      - name: Print version
        run: jolie --version
